---
- name: "Cloud / Google / Prepare package managers"
  vars:
    sys_repository:
      prepare: true
      deploy: true
      setup: true
      provision: true
    sys_repository_managers:
      flatpak: "{{ cloud_google_cli_application['type'] == 'flatpak' }}"
      snap: "{{ cloud_google_cli_application['type'] == 'snap' }}"
      git: "{{ cloud_google_cli_application['type'] == 'git' }}"
    sys_repository_catalog_distro: "{{ cloud_google_cli_repository_catalog_distro }}"
    sys_repository_catalog_yum: "{{ cloud_google_cli_repository_catalog_yum }}"
    sys_repository_catalog_apt: "{{ cloud_google_cli_repository_catalog_apt }}"
    sys_repository_custom_yum: "{{ cloud_google_cli_repository_custom_yum }}"
    sys_repository_custom_apt: "{{ cloud_google_cli_repository_custom_apt }}"
  ansible.builtin.include_role:
    name: "serdigital64.system.sys_repository"

- name: "Cloud / Google / Prepare package installer"
  vars:
    sys_package:
      prepare: true
  ansible.builtin.include_role:
    name: "serdigital64.system.sys_package"
...
