---
- name: "Cloud / Google / Initialize / Check Platform compatibility"
  ansible.builtin.assert:
    quiet: true
    fail_msg: "Target Platform not supported: {{ ansible_distribution + ansible_distribution_major_version }}"
    that:
      - ansible_distribution + ansible_distribution_major_version in cloud_google_cli_platforms

- name: "Cloud / Google / Initialize / Set Platform specific variables"
  ansible.builtin.include_vars:
    file: "{{ 'platform-' + cloud_google_cli_os_family + '.yml' }}"

- name: "Cloud / Google / Initialize / Resolve prerequisites"
  ansible.builtin.include_tasks:
    file: "cloud_google_cli_prerequisite.yml"
  when:
    - "'resolve_prereq' in cloud_google_cli"
    - cloud_google_cli['resolve_prereq']
...
