---
- name: "Prepare"
  hosts: "{{ lookup('env', 'DEVAP_TEST_PLATFORM') | default('all') }}"
  gather_facts: false
  tasks:

    - name: "Load common test vars"
      ansible.builtin.include_vars:
        file: "../test_vars.yml"

    - name: "Discover platform"
      ansible.builtin.setup:
        gather_subset: "min"
        gather_timeout: "10"

    - name: "Prepare"
      vars:
        cloud_google_cli:
          resolve_prereq: true
          prepare: true
        cloud_google_cli_application: "{{ test_cloud_google_cli_application_brew }}"
      ansible.builtin.include_role:
        name: "cloud_google_cli"
...
