---
cloud_aws_cli_platforms:
  - "CentOS8"
  - "RedHat8"
  - "AlmaLinux8"
  - "Rocky8"
  - "OracleLinux8"
  - "Ubuntu20"
  - "Ubuntu21"
  - "Ubuntu22"
  - "Fedora33"
  - "Fedora35"
  - "Fedora36"
  - "Debian10"
  - "Debian11"
  - "MacOSX12"

cloud_aws_cli_base:
  paths:
    brew:
      root: "/opt/aws"
      bin: "/opt/aws/bin"
      versions: "/opt/aws/versions"
    binary:
      root: "/opt/aws"
      bin: "/opt/aws/bin"
      versions: "/opt/aws/versions"
  run:
    brew:
      aws: "/opt/homebrew/bin/aws"
    binary:
      aws: "/opt/aws/bin/aws"
  files:
    install: "aws/install"
  access:
    user:
      root: "root"
    group:
      root: "root"
    mode:
      dir: "0755"
      file: "0644"
      exe: "0755"

cloud_aws_cli_profiles:
  brew:
    latest:
      packages:
        - name: "awscli"
  binary:
    latest:
      packages:
        - file: "awscli-exe-linux-x86_64.zip"
          uncompress: true
      origin: "https://awscli.amazonaws.com"
      script:
        - "{{ cloud_aws_cli_base['files']['install'] }}"
        - "--install-dir"
        - "{{ cloud_aws_cli_base['paths']['binary']['versions'] }}"
        - "--bin-dir"
        - "{{ cloud_aws_cli_base['paths']['binary']['bin'] }}"
        - "--update"

# cloud_aws_cli___prepare_path: ~
# cloud_aws_cli___prepare_cfg: ~
...
