---
cloud_aws_realm_users:
  - name: "blgmgr"
  - name: "blgadtr"
  - name: "iammgr"
  - name: "iamadtr"
  - name: "cloudmgr"
  - name: "cloudadtr"

cloud_aws_realm_groups:
  - name: "billing_managers"
    users:
      - "blgmgr"
  - name: "billing_auditors"
    users:
      - "blgadtr"
  - name: "iam_managers"
    users:
      - "iammgr"
  - name: "iam_auditors"
    users:
      - "iamadtr"
  - name: "cloud_managers"
    users:
      - "cloudmgr"
  - name: "cloud_auditors"
    users:
      - "cloudadtr"

cloud_aws_realm_account:
  id: "**changeme**"
  name: "**changeme**"

cloud_aws_realm_api:
  root:
    key: "**changeme**"
    secret: "**changeme**"
  iam_manager_auto:
    key: "**changeme**"
    secret: "**changeme**"
  cloud_manager_auto:
    key: "**changeme**"
    secret: "**changeme**"
...
