---
- name: "Cloud / AWS / Realm / Provision / Normalize credentials"
  ansible.builtin.set_fact:
    cloud_aws_realm___provision_iam:
      key: "{{
        cloud_aws_realm_api['root']['key'] |
        default(cloud_aws_realm_api['iam_manager_auto']['key'])
        }}"
      secret: "{{
        cloud_aws_realm_api['root']['secret'] |
        default(cloud_aws_realm_api['iam_manager_auto']['secret'])
        }}"

- name: "Cloud / AWS / Realm / Provision / Structure"
  ansible.builtin.include_tasks:
    file: "cloud_aws_realm_provision_structure.yml"

- name: "Cloud / AWS / Realm / Provision / Users"
  ansible.builtin.include_tasks:
    file: "cloud_aws_realm_provision_users.yml"
  when:
    - cloud_aws_realm_users is defined
    - cloud_aws_realm_users | length > 0

- name: "Cloud / AWS / Realm / Provision / Groups"
  ansible.builtin.include_tasks:
    file: "cloud_aws_realm_provision_groups.yml"
  when:
    - cloud_aws_realm_groups is defined
    - cloud_aws_realm_groups | length > 0
...
