---
- name: "Cloud / AWS / Realm / Provision / Groups / Assign members ({{ cloud_aws_realm___provision_group['name'] }})"
  community.aws.iam_group:
    aws_access_key: "{{ cloud_aws_realm___provision_iam['key'] }}"
    aws_secret_key: "{{ cloud_aws_realm___provision_iam['secret'] }}"
    name: "{{
      cloud_aws_realm_structure_groups[cloud_aws_realm___provision_group['name']]
      ['name']
      }}"
    users: "{{ cloud_aws_realm___provision_group['users'] }}"
    state: "present"
    purge_users: true
    purge_policies: false
  loop: "{{ cloud_aws_realm_groups }}"
  loop_control:
    loop_var: "cloud_aws_realm___provision_group"
  when:
    - cloud_aws_realm___provision_group['name'] is defined
    - cloud_aws_realm___provision_group['name'] | length > 0
    - cloud_aws_realm___provision_group['users'] is defined
    - cloud_aws_realm___provision_group['users'] | length > 0
    - cloud_aws_realm_structure_groups[cloud_aws_realm___provision_group['name']] is defined
    - cloud_aws_realm_structure_groups[cloud_aws_realm___provision_group['name']]['private'] is defined
    - not cloud_aws_realm_structure_groups[cloud_aws_realm___provision_group['name']]['private']
...
