---
- name: "Cloud / AWS / Realm / Provision / Structure / Create IAM Policies"
  community.aws.iam_managed_policy:
    aws_access_key: "{{ cloud_aws_realm___provision_iam['key'] }}"
    aws_secret_key: "{{ cloud_aws_realm___provision_iam['secret'] }}"
    policy_name: "{{ cloud_aws_realm___provision_policy['value']['name'] }}"
    policy_description: "{{ cloud_aws_realm___provision_policy['value']['description'] }}"
    policy: "{{ lookup('template', cloud_aws_realm___provision_policy['value']['template']) }}"
    state: "present"
  loop: "{{ cloud_aws_realm_structure_policies | dict2items }}"
  loop_control:
    loop_var: "cloud_aws_realm___provision_policy"

- name: "Cloud / AWS / Realm / Provision / Structure / Create IAM Users for automated systems"
  community.aws.iam_user:
    aws_access_key: "{{ cloud_aws_realm___provision_iam['key'] }}"
    aws_secret_key: "{{ cloud_aws_realm___provision_iam['secret'] }}"
    name: "{{ cloud_aws_realm___provision_user_auto['value']['name'] }}"
    state: "present"
    purge_policies: true
  loop: "{{ cloud_aws_realm_structure_managers | dict2items }}"
  loop_control:
    loop_var: "cloud_aws_realm___provision_user_auto"

- name: "Cloud / AWS / Realm / Provision / Structure / Create IAM Groups"
  community.aws.iam_group:
    aws_access_key: "{{ cloud_aws_realm___provision_iam['key'] }}"
    aws_secret_key: "{{ cloud_aws_realm___provision_iam['secret'] }}"
    name: "{{ cloud_aws_realm___provision_group_auto['value']['name'] }}"
    managed_policies: "{{ cloud_aws_realm___provision_group_auto['value']['managed_policies'] | default(omit) }}"
    users: "{{ cloud_aws_realm___provision_group_auto['value']['users'] | default(omit) }}"
    state: "present"
    purge_policies: true
  loop: "{{ cloud_aws_realm_structure_groups | dict2items }}"
  loop_control:
    loop_var: "cloud_aws_realm___provision_group_auto"
...
