---
- name: "Cloud / Foundry / CLI / Initialize / Check Platform compatibility"
  ansible.builtin.assert:
    quiet: true
    fail_msg: "Target Platform not supported: {{ ansible_distribution + ansible_distribution_major_version }}"
    that:
      - ansible_distribution + ansible_distribution_major_version in cloud_foundry_cli_platforms

- name: "Cloud / Foundry / CLI / Initialize / Set Platform specific variables"
  ansible.builtin.include_vars:
    file: "platform-{{ cloud_foundry_cli_os_family }}.yml"

- name: "Cloud / Foundry / CLI / Initialize / Resolve prerequisites"
  ansible.builtin.include_tasks:
    file: "cloud_foundry_cli_prerequisite.yml"
  when:
    - "'resolve_prereq' in cloud_foundry_cli"
    - cloud_foundry_cli['resolve_prereq']
...
