---
- name: "Cloud / AWS / CLI / Initialize"
  ansible.builtin.include_tasks:
    file: "cloud_aws_cli_initialize.yml"

- name: "Cloud / AWS / CLI / Prepare"
  ansible.builtin.include_tasks:
    file: "cloud_aws_cli_prepare.yml"
  when:
    - "'prepare' in cloud_aws_cli"
    - cloud_aws_cli['prepare']

- name: "Cloud / AWS / CLI / Deploy"
  ansible.builtin.include_tasks:
    file: "cloud_aws_cli_deploy.yml"
  when:
    - "'deploy' in cloud_aws_cli"
    - cloud_aws_cli['deploy']

- name: "Cloud / AWS / CLI / Finalize"
  ansible.builtin.include_tasks:
    file: "cloud_aws_cli_finalize.yml"
...
